-- Generated by nwg-displays on 2026-08-23 at 13:16:28. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@165.0",
    position = "1440x1",
    scale = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1440x900@59.89",
    position = "0x860",
    scale = 1
})
